[0.000000] (-) TimerEvent: {}
[0.000602] (bi_agents) JobQueued: {'identifier': 'bi_agents', 'dependencies': OrderedDict()}
[0.000693] (ci_agents) JobQueued: {'identifier': 'ci_agents', 'dependencies': OrderedDict()}
[0.000758] (visitor_agents) JobQueued: {'identifier': 'visitor_agents', 'dependencies': OrderedDict()}
[0.000807] (bi_agents) JobStarted: {'identifier': 'bi_agents'}
[0.015943] (ci_agents) JobStarted: {'identifier': 'ci_agents'}
[0.020628] (visitor_agents) JobStarted: {'identifier': 'visitor_agents'}
[0.099312] (-) TimerEvent: {}
[0.199969] (-) TimerEvent: {}
[0.300335] (-) TimerEvent: {}
[0.400717] (-) TimerEvent: {}
[0.501042] (-) TimerEvent: {}
[0.601394] (-) TimerEvent: {}
[0.701748] (-) TimerEvent: {}
[0.802099] (-) TimerEvent: {}
[0.902491] (-) TimerEvent: {}
[0.912206] (visitor_agents) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.10/selectors.py", line 469, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 94, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 192, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'-W\', \'ignore:setup.py install is deprecated\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2866, in get_entry_map\n    ep_map = self._ep_map\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2828, in __getattr__\n    raise AttributeError(attr)\nAttributeError: _ep_map. Did you mean: \'_dep_map\'?\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/khushal/campus_tour_ws/src/visitor_agents/setup.py", line 5, in <module>\n    setup(\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 152, in setup\n    _install_setup_requires(attrs)\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 142, in _install_setup_requires\n    dist = MinimalDistribution(attrs)\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 134, in __init__\n    distutils.core.Distribution.__init__(self, filtered)\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 457, in __init__\n    for ep in pkg_resources.iter_entry_points(\'distutils.setup_keywords\'):\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 646, in <genexpr>\n    for entry in dist.get_entry_map(group).values()\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2868, in get_entry_map\n    ep_map = self._ep_map = EntryPoint.parse_map(\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2549, in parse_map\n    for group, lines in data:\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3205, in split_sections\n    for line in yield_lines(s):\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2781, in _get_metadata\n    yield line\nKeyboardInterrupt\n\n'}
[0.914666] (visitor_agents) JobEnded: {'identifier': 'visitor_agents', 'rc': 'SIGINT'}
[0.915096] (bi_agents) JobEnded: {'identifier': 'bi_agents', 'rc': 'SIGINT'}
[0.915449] (ci_agents) JobEnded: {'identifier': 'ci_agents', 'rc': 'SIGINT'}
[0.924162] (-) EventReactorShutdown: {}
